### ISSUE TITLE
[bug] Ability to add the same package twice

### ISSUE THREAD

**Issue by inoyakaigor** [rickbrenn/refit#3]
There is ability to add the same package:
![image](https://github.com/rickbrenn/refit/assets/1235286/cb319c4b-0f42-4227-94d2-408983a69599)

**Comment by rickbrenn** [comment]
I wanted to allow the same package to be selected from the wizard in the case that you want to add different versions of the package to different workspaces of a monorepo but then that leads to being able to add the same package twice to the same workspace. Maybe I'll change it so that if you select the same package for the same workspace it'll replace the existing one.

**Comment by rickbrenn** [comment]
Should be fixed now in the latest version https://github.com/rickbrenn/refit/releases/tag/v1.0.2
